<?php
declare(strict_types=1);

include_once('template/common.tpl.php');
?>

<?php function drawPrivacyPolicyContent()
{ ?>
    <main id="about-page">
        <h1>Privacy Policy</h1>
        <h2>Last updated: May 19, 2024</h2>
        <section>
            <h2>Overview</h2>
            <p>
                This Privacy Policy describes our policies and procedures on the collection,
                use and disclosure of your information when you use the Service and tells you
                about your privacy rights and how the law protects you.
                We use Your Personal data to provide and improve the Service. By using the
                Service, you agree to the collection and use of information in accordance with
                this Privacy Policy.
            </p>
        </section>
        <section>
            <h2>Interpretation</h2>
            <p>
                The words of which the initial letter is capitalized have meanings defined
                under the following conditions. The following definitions shall have the same
                meaning regardless of whether they appear in singular or in plural.
            </p>
        </section>
        <section>
            <h2>Definitions</h2>
            <p>For the purposes of this Privacy Policy:</p>
            <p>Account means a unique account created for You to access our Service or
                parts of our Service.</p>
            <p>Affiliate means an entity that controls, is controlled by or is under
                common control with a party, where "control" means ownership of 50% or
                more of the shares, equity interest or other securities entitled to vote
                for election of directors or other managing authority.</p>
            <p>Company (referred to as either "the Company", "We", "Us" or "Our" in this
                Agreement) refers to Trinted LLC, FEUP, Porto, Portugal.</p>
            <p>Cookies are small files that are placed on Your computer, mobile device or
                any other device by a website, containing the details of Your browsing
                history on that website among its many uses.</p>
            <p>Country refers to: Portugal</p>
            <p>Device means any device that can access the Service such as a computer, a
                cellphone or a digital tablet.</p>
            <p>Personal Data is any information that relates to an identified or
                identifiable individual.</p>
            <p>Service refers to the Website.</p>
            <p>Service Provider means any natural or legal person who processes the data
                on behalf of the Company. It refers to third-party companies or
                individuals employed by the Company to facilitate the Service, to provide
                the Service on behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is used.</p>
            <p>Usage Data refers to data collected automatically, either generated by the
                use of the Service or from the Service infrastructure itself (for example,
                the duration of a page visit).</p>
            <p>Website refers to Trinted.</p>
            <p>You means the individual accessing or using the Service, or the company,
                or other legal entity on behalf of which such individual is accessing or
                using the Service, as applicable.</p>
        </section>
    </main>
<?php } ?>

<?php
function drawPrivacyPolicyPage(Request $request)
{
    createPage(function () use (&$request) {
        drawMainHeader();
        drawPrivacyPolicyContent();
        drawFooter();
    });
} ?>